error_map = {
    0: None,
    -1: " connection service failure ",
    -2: " link authentication failure ",
    -3: " host address is not available ",
    -4: " send data error ",
    -5: " test numbers are not legitimate ",
    -6: " not ready to test network ",
    -7: " the current network testing is not over yet ",
    -8: " useless available access preamble ",
    -9: " data path is unavailable ",
    -10: " repeat login ",
    -11: " internal error ",
    -12: " the last time the request is not over yet ",
    -13: " input parameters illegal ",
    -14: " authorization code is not legitimate ",
    -15: " extended authorization code ",
    -16: " authorization code type mismatch ",
    -17: "API not ready ",
    -18: "UDP port monitor fail ",
    -19: "UDP we are listening ",
    -20: " the interface is not implemented ",
    -21: " each landing only allowed to call once ",
    -22: " more than at a single frequency 。",
    -10000: " input data NULL",
    -10001: " input errors :TAPIYNFLAG",
    -10002: " input errors :TAPILOGLEVEL",
    -10003: " input errors :TAPICommodityType",
    -10004: " input errors :TAPICallOrPutFlagType",
    -12001: " input errors :TAPIAccountType",
    -12003: " input errors :TAPIAccountState",
    -12004: " input errors :TAPIAccountFamilyType",
    -12005: " input errors :TAPIOrderTypeType",
    -12006: " input errors :TAPIOrderSourceType",
    -12007: " input errors :TAPITimeInForceType",
    -12008: " input errors :TAPISideType",
    -12009: " input errors :TAPIPositionEffectType",
    -12010: " input errors :TAPIHedgeFlagType",
    -12011: " input errors :TAPIOrderStateType",
    -12012: " input errors :TAPICalculateModeType",
    -12013: " input errors :TAPIMatchSourceType",
    -12014: " input errors :TAPIOpenCloseModeType",
    -12015: " input errors :TAPIFutureAlgType",
    -12016: " input errors :TAPIOptionAlgType",
    -12017: " input errors :TAPIBankAccountLWFlagType",
    -12021: " input errors :TAPIMarginCalculateModeType",
    -12022: " input errors :TAPIOptionMarginCalculateModeType",
    -12023: " input errors :TAPICmbDirectType",
    -12024: " input errors :TAPIDeliveryModeType",
    -12025: " input errors :TAPIContractTypeType",
    -12035: " input errors :TAPITacticsTypeType",
    -12036: " input errors :TAPIORDERACT",
    -12041: " input errors :TAPITriggerConditionType",
    -12042: " input errors :TAPITriggerPriceTypeType",
    -12043: " input errors :TAPITradingStateType",
    -12044: " input errors :TAPIMarketLevelType",
    -12045: " input errors :TAPIOrderQryTypeType",
    1: " initiative calls ",
    2: " passive disconnect ",
    3: " read error ",
    4: " write error ",
    5: " the buffer is full ",
    6: " asynchronous operation errors ",
    7: " error parsing data ",
    8: " connection timed out ",
    9: " initialization failed ",
    10: " already connected ",
    11: " worker thread has ended ",
    12: " operation is in progress ， please try again later ",
    13: " heartbeat failure ",
    10001: " login process execution error ",
    10002: " login user does not exist ",
    10003: " the need for dynamic authentication ",
    10004: " log unauthorized users ",
    10005: " incorrect login module ",
    10006: " you need to force change password ",
    10007: " login state is prohibited landing ",
    10008: " login password is not correct ",
    10009: " without this module login rights ",
    10010: " number login overrun ",
    10011: " log in under the user is not logged-on user may identify the server list ",
    10012: " login user has been frozen ",
    10013: " wrong password ， users freeze ",
    10014: " state does not allow customers to log ",
    10015: " the need for secondary certification ",
    10016: None,
    10017: None,
    10018: " login password more than the number of days ",
    10101: " login user information lookup failed ",
    11001: " database operation failed ",
    11501: " all funds under the logged-on user account query fails ",
    11701: " login user password modification fails ",
    11702: " login user password modification fails —— original password error ",
    11703: " login user password modification fails —— and not before n the same password twice ",
    11704: " the new password does not meet password complexity requirements ",
    20201: " financial account information query fails ",
    20701: " customer trading code query fails ",
    22801: " contract information query fails ",
    22901: " special options subject query fails ",
    25501: " variety delegate type query fails ",
    25601: " variety commissioned time validity query fails ",
    28901: " single user frequency query fails ",
    60001: " capital account does not exist ",
    60002: " capital account status is incorrect ",
    60003: " capital account trading center inconsistent ",
    60004: " funding options trading account without permission ",
    60005: " capital account transactions without permission varieties ",
    60006: " open capital accounts without permission ",
    60007: " funds account risk control entry check fails ",
    60011: " single contract invalid ",
    60021: " customer permission is prohibited transaction ",
    60022: " customer grouping varieties prohibited transaction ",
    60023: " customer contracts ad hoc trading ban ",
    60024: " prohibit trading system privileges ",
    60031: " positions exceed the maximum limit ",
    60032: " single orders exceeding the maximum amount ",
    60033: " no single contract transaction routing ",
    60034: " price departing from the scope beyond the commission ",
    60035: " exceed GiveUp largest positions ",
    60036: " single automatic audit failure ",
    60037: "LME not ready ",
    60038: " open the wrong way ",
    60039: " single parent account corresponding lack of funds ",
    60040: " single swap contracts malformed ",
    60051: " lack of funds orders ",
    60052: " fee parameter error ",
    60053: " margin parameter error ",
    60061: " no withdrawals, no such system ",
    60062: " this state does not allow withdrawals ",
    60063: " single record does not allow withdrawals ",
    60071: " this state is not allowed to change a single ",
    60072: " artificial single single not allowed to change ",
    60081: " deleted declaration can not be transferred ",
    60082: " artificial single single not allowed to change ",
    60091: " recorded single repeat ",
    60092: " margin parameter error ",
    60100: " only query operations account ",
    60101: " market price contract modification failed ",
    60102: " even sub-account is a market maker price should not be ",
    60103: " orders can not find the trading code ",
    60104: " operating account only open ",
    60105: " not on account of operating rights pending inquiry ",
    60106: " effective single deadline can not be less than the current trading day ",
    60107: " the encoder resolution is not allowed to apply or combination ",
    60108: " this non-labeled account server allowed to operate under ",
    60109: " exercise or abstain exceeds the available amount ",
    60110: " no orders audit authority ",
    60111: " single orders exceeding the maximum amount to get started ",
    60115: " dalian should not allow non-price inconsistencies two single pen amount of commission ",
    60117: " application does not allow duplicate submission ",
    60118: " more than an account at a single frequency limit ",
    60119: " combination table does not exist or a combination of a direction flag insured ",
    61001: " order the operating frequency is too high ",
    61002: " queries can not be commissioned before the next query returns ",
    72001: " the maximum total number of subscriptions exceeded market ",
    72002: " subscribe to exceed the maximum number of the exchange market ",
    72101: " no subscription rights in the market ",
    72102: " no subscription rights under the stock exchange quotes ",
    72103: " variety does not exist ",
    72104: " contracts may not exist ",
    83001: " the market does not support the protocol ",
    14001: " secondary verification fails ",
    14002: " secondary authentication timeout ",
    11000: " database connection failed ",
    11002: " does not allow one to many ",
    11003: " failed to delete - an association information ，",
    11004: " delete group failed - there are groups subordinate or subordinates operator ",
    12001: " login user password modification fails - original password error ",
    12002: " login user password modification fails - and not before n the same password twice ",
    12003: " login user password modification fails - the new password does not meet password complexity requirements ",
    13001: " a currency group can only set a base currency ",
    13002: " only the base currency is us dollars or hong kong dollars ",
    60012: "LME not ready ",
    60013: " does not support the type of orders ",
    60014: " wrong type of bill ",
    60015: " illegal delegate type ",
    60025: " client privilege only open ",
    60026: " customer contracts can only be ad hoc open ",
    60027: " only open system privileges ",
    60028: " only open a few days in advance limit can only be liquidated ",
    60029: " customer varieties of risk control permission is prohibited transaction ",
    60030: " customer varieties of risk control authority may only be liquidated ",
    60041: " not logged gateway ",
    60042: " gateway information not found ",
    60054: " the total capital base currency shortage ",
    60055: " exceed the amount of margin ",
    60056: " the total credits over the opening ratio limit yl ",
    60057: " independent currency group than the opening ratio limit ",
    60058: " risk array parameter error ",
    60073: " risk is not allowed to change a single declaration ",
    60074: " the amount of change is larger than a single daily ",
    60075: " not allowed to change a single embedded single ",
    60112: " under the single largest positions than to get started ",
    60121: " kaiping wrong way ",
    60122: " lack of trust open positions ",
    60123: " closing the transaction fails ",
    60131: " local commission found ",
    60132: " disconnect from gateway ",
    60141: " repeat recorded single transaction ",
    60142: " recorded single transaction corresponding to the commission found ",
    60143: " there is no single record contracts ",
    60144: " recorded single transaction parameter error ",
    60145: " recorded single transaction commission state error ",
    60151: " delete traded turnover was not found ",
    60152: " this status deal can not be deleted ",
    60161: " this status does not allow entry orders ",
    60162: " wrong change order request ",
    60163: " orders can not be deleted ， there is a corresponding transaction ",
    60164: " unlawful state commission ",
    60165: " this state does not allow the transfer orders ",
    60166: " orders can not be deleted ",
    60171: " no withdrawals maker bilateral commission found ",
    60172: " bilateral market makers is inconsistent customer withdrawals ",
    60173: " market maker bilateral cancellation varieties inconsistent ",
    60174: " market makers is inconsistent bilateral contract cancellation ",
    60175: " bilateral trade market maker withdrawals same direction ",
    60176: " bilateral trade market makers cancellation wrong direction ",
    60177: " market makers unilaterally check failed ",
    60181: " pay activation fails ， order not found ",
    60182: " pay activation fails ， non-active state ",
    80001: " gateway is not ready ， no connection to get started ",
    80002: " variety error ",
    80003: " error contract ",
    80004: " field is incorrect declaration ",
    80005: " the price is not legitimate ",
    80006: " number of illegal ",
    80007: " declaration type is not legitimate ",
    80008: " principal mode illegal ",
    80009: " delegate does not exist （ change orders 、 withdrawals ）",
    80010: " failure to send declaration ",
    80011: " he refused to be started ",
    90001: " the module does not allow pre-login ",
    90002: " a request too much data ",
    90003: " to the front there is no data ",
    90004: " the operator information request is absent. ",
    90011: " front disconnected from the transaction ",
    90012: " front and disconnect management ",
    90021: " subordinate capital account does not exist ",
    90022: " the operator does not permit trade ",
    90023: " query too frequently ",
    90024: " this authorization shall not promise login ",
    90025: " since the transaction authentication fails ",
    -23: " query too frequently 。",
    -24: " does not meet the conditions call 。",
    -25: " did not find the corresponding single change orders when withdrawals 。",
    -26: " log path is empty 。",
    -27: " failed to open the log file ",
    -28: " no trader login rights ",
    -29: " no order entry or transaction entry ",
    -30: " no orders to modify and delete permissions orders ， turnover delete permissions ",
    -31: " no orders transfer of authority ",
    -32: " when the number of transactions entered into the system is empty ",
    -33: " upon completion delete transaction number is empty 。",
    -34: " corresponding transaction did not find the time to delete the transaction ",
    -35: " change orders when modifying customer accounts 。",
    -36: " when there is no change in orders for the transfer customer accounts ",
    -37: " telephone number of passwords to modify wrong or contain special characters 。",
    -38: " unbound secondary authentication information ",
    -39: " can no longer apply for a secondary authentication code within secondary certification is valid ",
    -40: " client privilege is not set password 。",
    -41: " single customer risk policy can not be revoked or changed ",
    -42: " change a single customer account and fill customer orders inconsistent accounts ",
    -11001: " input errors :TAPIBucketDateFlag",
    -11002: " input errors :TAPIHisQuoteType",
    -12002: " input errors :TAPIUserTypeType",
    -12018: " input errors :TAPIBankAccountStateType",
    -12019: " input errors :TAPIBankAccountSwapStateType",
    -12020: " input errors :TAPIBankAccountTransferStateType",
    -12026: " input errors :TAPIPartyTypeType",
    -12027: " input errors :TAPIPartyCertificateTypeType",
    -12028: " input errors :TAPIMsgReceiverType",
    -12029: " input errors :TAPIMsgTypeType",
    -12030: " input errors :TAPIMsgLevelType",
    -12031: " input errors :TAPITransferDirectType",
    -12032: " input errors :TAPITransferStateType",
    -12033: " input errors :TAPITransferTypeType",
    -12034: " input errors :TAPITransferDeviceIDType",
    -12037: " input errors :TAPIBillTypeType",
    -12038: " input errors :TAPIBillFileTypeType",
    -12039: " input errors :TAPIOFFFlagType",
    -12040: " input errors :TAPICashAdjustTypeType",
    -12046: " input errors : ClientID，ClientID it contains special characters 。",
    -13001: " historical quotes query parameters are not legitimate ",
    -13002: " price and quantity contained in NAN or INF illegal value ",
    -12047: " input errors due date ",
    -12048: " wrong password type ",
    -12049: " wrong type of settlement data ",
}
