from vnpy.api.oes.vnoes import OesApi_GetErrorMsg, OesApi_GetLastError


def error_to_str(code: int):
    try:
        # return error_codes[code]
        return OesApi_GetErrorMsg(code)
    except KeyError:
        return "Unknown error code!"


def get_last_error():
    code = OesApi_GetLastError()
    return OesApi_GetErrorMsg(code)


error_codes = {
    1001: " error message format ",
    1002: " the current host is not the master node ",
    1003: " library operation failed main memory ",
    1004: " depending on the state and other basic data does not match ， unable to update data ",
    1005: " protocol version incompatible ",
    1006: " data does not exist ",
    1007: " service opening hours does not arrive ",
    1008: " illegal cursor positioning ",
    1009: " illegal client login user name ",
    1010: " illegal securities code ",
    1011: " illegal customer code ",
    1012: " illegal client type ",
    1013: " the client has been disabled ",
    1014: " the client password is incorrect ",
    1015: " repeat client login ",
    1016: " the number of clients connect too many ",
    1017: " client accounts of others unauthorized operation ",
    1018: " modified beyond the scope of data ",
    1019: " illegal application name ",
    1020: " request condition conflict ",
    1021: " illegal clients IP/MAC address format ",
    1022: " this business is not yet supported ",
    1023: " the number of illegal client environment ",
    1024: " exchange rejected ",
    1025: " cabinet rejected ",
    1026: " traffic over the limits ",
    1027: " prohibit the use of API log in ",
    1028: " illegal private equity fund product code ",
    1029: " password unchanged ",
    1030: " illegal source categories ",
    1031: " illegal type of encryption ",
    1032: " illegal client device serial number ",
    1033: " no available node ",
    1101: " login failed counter ",
    1102: " failure to report the counter ",
    1103: " obtained from the counter state failure ",
    1201: " illegal securities account codes ",
    1202: " illegal capital account codes ",
    1203: " illegal access to payment direction ",
    1204: " illegal market code ",
    1205: " illegal securities category ",
    1206: " illegal sale of type ",
    1207: " illegal currency ",
    1208: " illegal delegate type ",
    1209: " invalid account status ",
    1210: " request information not found ",
    1211: " position information not found ",
    1212: " gold out of the water is not found ",
    1213: " repeat serial number ",
    1214: " the current period can not offer ",
    1215: " no operating authority ",
    1216: " available / less than desirable balance of funds ",
    1217: " lack of available positions ",
    1218: " the number of commission is not legal within the range ",
    1219: " non-integer multiples of the number of units ",
    1220: " unlawful PBU code ",
    1221: " price is not legal within the range ",
    1222: " non-integer multiple of the unit price ",
    1223: " no limit price of market order fail ",
    1224: " the current period is not supported by market order ",
    1225: " invalid order status ",
    1226: " cancellation information does not match with the original commission ",
    1227: " repeat withdrawals ",
    1228: " position limit check failed ",
    1229: " purchase check failed ",
    1230: " exceeded ETF the largest proportion of cash alternative ",
    1231: " non-exercise date ",
    1232: " product （ securities ） suspension ",
    1233: " contractual restrictions open ",
    1234: " day total subscription or redemption amount exceeds the limit ",
    1235: " i. the number of the day or the cumulative net redemptions exceed the limit ",
    1236: " can not find previous closing price ",
    1237: " daily withdrawal limit exceeding ratio ",
    1238: " delegation request is too frequent ",
    1239: " illegal access to payment transfer amount ",
    1240: " repeat subscription commission ",
    1241: " copies subscription amount over subscription commission ",
    1242: " limit access to payment amount in more than ",
    1243: " at the same time ban to do more gold out of the pen ",
    1244: " the number of new shares with illegal 、 winning record type ",
    1245: " limit shareholder accounts buy transaction ",
    1246: " limit shareholders sell transaction accounts ",
    1247: " limit shareholder accounts reverse repurchase transactions ",
    1248: " limiting shareholders to subscribe for new shares trading accounts ",
    1249: " shareholder account does not have permission market order trade ",
    1250: " shareholder account no transaction permission of securities on gem ",
    1251: " shareholder account no trading rights grading fund ",
    1252: " no shareholder accounts qfii authority bonds ",
    1253: " customer risk rating lower than the risk level of demand for securities trading ",
    1254: " shareholder account does not have permission securities trading risk warning ",
    1255: " shareholders do not have permission trading account securities delisting finishing ",
    1256: " no single shareholder account trading market ETF permission ",
    1257: " shareholders account does not cross-market trading ETF permission ",
    1258: " no shareholder account transactions monetary fund ETF permission ",
    1259: " no cross-border transactions shareholder account ETF permission ",
    1260: " allow only qualified investors to invest in such securities ",
    1261: " allow only qualified institutional investors to invest in such securities ",
    1262: " gold out of abnormality ， to be human intervention ",
    1263: " trading day period is not the issue of securities ",
    1264: "ETF product prohibit purchase ",
    1265: "ETF product prohibit redemption ",
    1266: " limit shareholder accounts specified withdrawal ",
    1267: " limit shareholder accounts for custody transfer ",
    1268: " institutional clients / cabinet business is not supported by bank transfer ",
    1269: " can not buy securities is prohibited open ",
    1270: " you can not buy securities blacklist ",
    1271: " shareholder account no trading authority depositary receipts ",
    1272: " permissions shareholder accounts did not trade stock enterprise innovation ",
    1273: " illegal access to payment transfer type ",

}
