NAME_DISPLAY_MAP = {
    "vt_symbol": " native code ",
    "direction": " direction ",
    "price": " price ",
    "volume": " quantity ",
    "time": " execution time （ second ）",
    "interval": " each round interval （ second ）",
    "offset": " offset ",
    "active": " algorithmic state ",
    "traded": " the number of transactions ",
    "order_volume": " single delegate ",
    "timer_count": " countdown round ",
    "total_count": " cumulative countdown ",
    "template_name": " algorithm template ",
    "display_volume": " number hang out ",
    "stop_price": " trigger price ",
    "price_add": " commissioned super price ",
    "step_price": " trading grid spacing ",
    "step_volume": " grid number of transactions ",
    "order_type": " types of ",
    "active_vt_symbol": " initiative leg ",
    "passive_vt_symbol": " passive leg ",
    "spread_up": " spread limit ",
    "spread_down": " spread limit ",
    "max_pos": " max open "
}
